USE [master]
GO

/****** Object:  Database [CoinDatabase]    Script Date: 2020/10/10 23:56:47 ******/
CREATE DATABASE [CoinDatabase]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'CoinDatabase', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\CoinDatabase.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'CoinDatabase_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\CoinDatabase_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [CoinDatabase].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [CoinDatabase] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [CoinDatabase] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [CoinDatabase] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [CoinDatabase] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [CoinDatabase] SET ARITHABORT OFF 
GO

ALTER DATABASE [CoinDatabase] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [CoinDatabase] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [CoinDatabase] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [CoinDatabase] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [CoinDatabase] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [CoinDatabase] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [CoinDatabase] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [CoinDatabase] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [CoinDatabase] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [CoinDatabase] SET  DISABLE_BROKER 
GO

ALTER DATABASE [CoinDatabase] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [CoinDatabase] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [CoinDatabase] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [CoinDatabase] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [CoinDatabase] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [CoinDatabase] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [CoinDatabase] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [CoinDatabase] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [CoinDatabase] SET  MULTI_USER 
GO

ALTER DATABASE [CoinDatabase] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [CoinDatabase] SET DB_CHAINING OFF 
GO

ALTER DATABASE [CoinDatabase] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [CoinDatabase] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [CoinDatabase] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [CoinDatabase] SET QUERY_STORE = OFF
GO

ALTER DATABASE [CoinDatabase] SET  READ_WRITE 
GO

USE [CoinDatabase]
GO
/****** Object:  Table [dbo].[tb_CoinJar]    Script Date: 2020/10/10 15:36:25 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[tb_CoinJar](
	[Amount] [decimal](18, 2) NULL,
	[Volume] [decimal](18, 2) NULL
) ON [PRIMARY]
GO
/****** Object:  StoredProcedure [dbo].[Sp_AddCoin]    Script Date: 2020/10/10 15:36:25 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[Sp_AddCoin]

	 @Amount DECIMAL(18,2),
	 @Volume DECIMAL(18,2)

AS
BEGIN
	
	SET NOCOUNT ON;

	INSERT INTO tb_CoinJar
	(
	  Amount,
	  Volume
	  )
	  VALUES
	  (
	  @Amount,
	  @Volume
	  )
 
END
GO
/****** Object:  StoredProcedure [dbo].[Sp_GetTotalAmount]    Script Date: 2020/10/10 15:36:25 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[Sp_GetTotalAmount]

AS
BEGIN
	
	SET NOCOUNT ON;

	Select Sum(Amount) FROM tb_CoinJar
 
END
GO
/****** Object:  StoredProcedure [dbo].[Sp_GetTotalVolume]    Script Date: 2020/10/10 15:36:25 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[Sp_GetTotalVolume]

AS
BEGIN
	
	SET NOCOUNT ON;

	Select Sum(Volume) FROM tb_CoinJar
 
END
GO
/****** Object:  StoredProcedure [dbo].[Sp_Reset]    Script Date: 2020/10/10 15:36:25 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[Sp_Reset]

AS
BEGIN
	
	SET NOCOUNT ON;

	DELETE FROM tb_CoinJar
 
END
GO
